---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubeovn.ustc.io
  resources:
  - vpcdns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeovn.ustc.io
  resources:
  - vpcdns/finalizers
  verbs:
  - update
- apiGroups:
  - kubeovn.ustc.io
  resources:
  - vpcdns/status
  verbs:
  - get
  - patch
  - update
