# permissions for end users to edit vpcconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vpcconnection-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vpcconnection
    app.kubernetes.io/part-of: vpcconnection
    app.kubernetes.io/managed-by: kustomize
  name: vpcconnection-editor-role
rules:
- apiGroups:
  - test.my.domain
  resources:
  - vpcconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.my.domain
  resources:
  - vpcconnections/status
  verbs:
  - get
