# permissions for end users to edit vpcdns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vpcdns-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multi-vpc
    app.kubernetes.io/part-of: multi-vpc
    app.kubernetes.io/managed-by: kustomize
  name: vpcdns-editor-role
rules:
- apiGroups:
  - kubeovn.ustc.io.my.domain
  resources:
  - vpcdns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeovn.ustc.io.my.domain
  resources:
  - vpcdns/status
  verbs:
  - get
